runtime: nodejs20

handlers:
  # Serve all static files from the dist directory
  - url: /(.*)
    static_files: dist/\1
    upload: dist/(.*)
    secure: always

  # Fallback all other routes to index.html (SPA)
  - url: /.*
    static_files: dist/main.jsx
    upload: dist/main.jsx
    secure: always